"""Per-site scraping configurations for Czech industry events.

Each config defines the event metadata and extraction rules.
For static sites, CSS selectors are used with BeautifulSoup.
For dynamic sites, a scraper_type flag tells the dispatcher to use Playwright or manual import.
"""

EVENTS = {
    "game_access": {
        "event_name": "Game Access Conference '26",
        "url": "https://game-access.com/conference/",
        "event_date": "2026-05-29",
        "event_end_date": "2026-05-30",
        "location": "BVV, Hall P, Brno, Czech Republic",
        "industry_focus": "M&E",
        "relevance_score": 6,
        "scraper_type": "static",
        "event_type_detail": "Conference + Expo (Act IX)",
        "expected_attendees": "2,000+ (12,000 sqm venue)",
        "audience": "Game developers, indie studios, publishers, students",
        "goal": "Network with CZ game studios, identify Maya/3ds Max/M&E Collection opportunities",
        "autodesk_relevance": "Maya, 3ds Max, MotionBuilder, M&E Collection, Arnold — core tools for game dev",
        "price": "Lite 4,300 CZK (~€176), Developer 5,500 CZK (~€226), Premium Business 7,700 CZK (~€315)",
        "agenda_highlights": "10 tracks, 80+ speakers, 100 indie showcase spots, 3 parties, B2B matchmaking",
        "organizer_contacts": {
            "organizer": "GameDev Area Czech s.r.o.",
            "partnership_email": "partners@game-access.com",
            "general_email": "info@game-access.com",
            "company_email": "contact@gamedevarea.com",
            "indie_showcase_email": "showcase@game-access.com",
            "company_address": "Slovákova 279/11, Veveří, 602 00 Brno",
            "ico": "02173298",
            "notes": "No phone listed publicly — email only. Use partners@ for sponsorship/attendee list. contact@gamedevarea.com for the parent company.",
        },
        "pages": [
            {
                "url": "https://game-access.com/conference/",
                "extractions": [
                    {
                        "type": "speakers",
                        "container_selector": ".speakers-grid .speaker-card, .elementor-widget-container .speaker-card, [class*='speaker']",
                        "name_selector": "h3, .speaker-name, .name",
                        "title_selector": ".speaker-role, .role, p",
                        "company_selector": ".speaker-company, .company",
                    },
                    {
                        "type": "partners",
                        "container_selector": ".partners-section img, .partner img, [class*='partner'] img",
                        "name_from": "alt",
                    },
                ],
            },
        ],
        "fallback_companies": [
            {"company_name": "Hangar 13", "role": "sponsor"},
            {"company_name": "Bohemia Interactive", "role": "sponsor"},
            {"company_name": "Warhorse Studios", "role": "sponsor"},
            {"company_name": "GRIP Studios", "role": "sponsor"},
            {"company_name": "Ninerocks Games", "role": "sponsor"},
            {"company_name": "Alda Games", "role": "sponsor"},
            {"company_name": "Ingame Studios", "role": "sponsor"},
            {"company_name": "JetBrains", "role": "sponsor"},
            {"company_name": "Audiokinetic", "role": "sponsor"},
            {"company_name": "Fanatic Games", "role": "sponsor"},
            {"company_name": "Studio 727", "role": "sponsor"},
            {"company_name": "Giants Software", "role": "sponsor"},
            {"company_name": "Photon", "role": "sponsor"},
            {"company_name": "PowerPlay Studio", "role": "sponsor"},
            {"company_name": "Arkance Systems", "role": "partner"},
        ],
        "fallback_speakers": [
            {"person_name": "Nate Purkeypile", "person_title": "Founder and Game Creator", "company_name": "Independent"},
            {"person_name": "Astrid Refstrup", "person_title": "CEO", "company_name": "Independent"},
            {"person_name": "Travis Gibson", "person_title": "Senior Business Development Manager", "company_name": "Independent"},
            {"person_name": "Jason Eyre", "person_title": "Director Business Development", "company_name": "Independent"},
        ],
    },

    "3dise": {
        "event_name": "3DISE Conference 2026",
        "url": "https://3dise.com/",
        "event_date": "2026-05-05",
        "event_end_date": "2026-05-06",
        "location": "Prague, Czech Republic",
        "industry_focus": "AEC",
        "relevance_score": 9,
        "scraper_type": "static",
        "event_type_detail": "Conference + Exhibition (2nd edition)",
        "expected_attendees": "300+",
        "audience": "3D scanning, reality capture, digital twins, heritage preservation professionals",
        "goal": "Showcase ReCap, Forma, ACC; connect with 3D scanning / reality capture ecosystem",
        "autodesk_relevance": "ReCap Pro, Forma, ACC, Revit, Civil 3D — reality capture to BIM pipeline",
        "price": "Regular €499, VIP €1,299 (excl. VAT)",
        "agenda_highlights": "30+ speakers, 2-day program, VIP boat tour, networking reception, exhibitor hall, Fuck-Up Night",
        "organizer_contacts": {
            "organizer": "3DISE s.r.o. (Michal Gula & Tomas Barnas)",
            "general_email": "info@3dise.com",
            "phone": "+421 907 475 49",
            "company_address": "Hvězdova 1716/2b, Nusle, Praha 4, 140 00",
            "ico_vat": "CZ23744847",
            "venue": "CUBEX Centre Prague, Na Strži 2097/63, Praha 4",
            "notes": "Small, founder-run event. Contact info@3dise.com for partnership/exhibitor booth or complimentary pass. Founders accessible via LinkedIn.",
        },
        "pages": [
            {
                "url": "https://3dise.com/",
                "extractions": [
                    {
                        "type": "speakers",
                        "container_selector": ".speaker-card, [class*='speaker'] .elementor-widget-container",
                        "name_selector": "h3",
                        "title_selector": "p, .speaker-role",
                        "linkedin_selector": "a[href*='linkedin']",
                    },
                    {
                        "type": "exhibitors",
                        "container_selector": ".exhibitors img, [class*='exhibitor'] img",
                        "name_from": "alt",
                    },
                    {
                        "type": "partners",
                        "container_selector": ".partners img, [class*='partner'] img",
                        "name_from": "alt",
                    },
                ],
            },
        ],
        "fallback_companies": [
            {"company_name": "Trimble", "role": "partner", "company_domain": "trimble.com"},
            {"company_name": "Xgrids", "role": "partner", "company_domain": "xgrids.com"},
            {"company_name": "Esri", "role": "partner", "company_domain": "esri.com"},
            {"company_name": "Sony Electronics", "role": "partner", "company_domain": "sony.com"},
            {"company_name": "Nubigon", "role": "partner", "company_domain": "nubigon.com"},
            {"company_name": "Overhead4D", "role": "partner", "company_domain": "overhead4d.com"},
            {"company_name": "Nira", "role": "partner", "company_domain": "nira.app"},
            {"company_name": "Ingos3d", "role": "partner", "company_domain": "ingos3d.com"},
            {"company_name": "Twinzo", "role": "exhibitor", "company_domain": "twinzo.eu"},
            {"company_name": "Scan3d", "role": "exhibitor"},
            {"company_name": "Mosaic", "role": "exhibitor"},
            {"company_name": "Skynamic", "role": "exhibitor"},
            {"company_name": "SAPIE", "role": "partner"},
            {"company_name": "Epic Games", "role": "speaker_company", "company_domain": "epicgames.com"},
            {"company_name": "ICONEM", "role": "speaker_company"},
            {"company_name": "CyArk", "role": "speaker_company"},
            {"company_name": "PIXOMONDO", "role": "speaker_company"},
            {"company_name": "RiVR", "role": "speaker_company"},
        ],
        "fallback_speakers": [
            {"person_name": "Tomas Barnas", "person_title": "Founder and CEO at Overhead4D", "company_name": "Overhead4D"},
            {"person_name": "Michal Ukropec", "person_title": "CEO at twinzo", "company_name": "Twinzo"},
            {"person_name": "Arkadiusz Szadkowski", "person_title": "International Sales Manager", "company_name": "Esri"},
            {"person_name": "Kenny Nakamura", "person_title": "Manager of Product and Business Development", "company_name": "Sony Electronics"},
            {"person_name": "Nikola Jancovicova", "person_title": "Business Development", "company_name": "Epic Games"},
            {"person_name": "Szymon Bloch", "person_title": "CEO", "company_name": "Scan3d"},
            {"person_name": "John Ristevski", "person_title": "Chairman and CEO", "company_name": "CyArk"},
            {"person_name": "Bachaar Tarabay", "person_title": "Head of Scientific Projects", "company_name": "ICONEM"},
            {"person_name": "Sam Munro", "person_title": "Senior Product Manager", "company_name": "PIXOMONDO"},
        ],
    },

    "connected_construction": {
        "event_name": "Connected Construction Days 2026",
        "url": "https://connectedconstructiondays.cz/",
        "event_date": "2026-05-26",
        "event_end_date": "2026-05-28",
        "location": "OREA Congress Hotel Brno + Pískovna Hrušovany (Day 3)",
        "industry_focus": "AEC",
        "relevance_score": 10,
        "scraper_type": "static",
        "event_type_detail": "3-day Conference + Workshops + Offsite EXPO",
        "expected_attendees": "300+",
        "audience": "Construction companies, surveyors, site managers, BIM coordinators",
        "goal": "Position ACC, BIM Collaborate Pro; partner presence with Trimble/SITECH",
        "autodesk_relevance": "ACC, BIM Collaborate Pro, Revit, Navisworks, Civil 3D — full construction workflow",
        "price": "Full Pass 3 days: €286 early bird / €411 standard; Offsite only: €187",
        "agenda_highlights": "Day 1-2: conference + 50 workshops + Indoor EXPO; Day 3: Offsite EXPO with live machine demos in quarry",
        "organizer_contacts": {
            "organizer": "SITECH CZ s.r.o. (+ Trimble, Construsoft, Geotronics)",
            "partnership_email": "partners@connectedconstructiondays.cz",
            "sitech_email": "info@sitech-czech.cz",
            "sitech_phone": "+420 733 738 481",
            "notes": "Explicitly invite partners — 3 tiers of technology partnership. Use partnership email for booth/sponsorship/free tickets.",
        },
        "pages": [{"url": "https://connectedconstructiondays.cz/"}],
        "fallback_companies": [
            {"company_name": "Trimble", "role": "organizer", "company_domain": "trimble.com"},
            {"company_name": "SITECH", "role": "organizer", "company_domain": "sitech.com"},
            {"company_name": "Construsoft", "role": "organizer", "company_domain": "construsoft.com"},
            {"company_name": "Geotronics", "role": "organizer"},
            {"company_name": "Terra", "role": "partner"},
            {"company_name": "Liebherr", "role": "partner", "company_domain": "liebherr.com"},
            {"company_name": "Bobcat", "role": "partner", "company_domain": "bobcat.com"},
            {"company_name": "CVUT", "role": "partner"},
            {"company_name": "ASC", "role": "partner"},
            {"company_name": "Cime", "role": "partner"},
            {"company_name": "ABM", "role": "partner"},
            {"company_name": "Garnea", "role": "partner"},
        ],
    },

    "lean_summit": {
        "event_name": "Lean Summit CzechoSlovakia 2026",
        "url": "https://beexcellent.cz/lean-summit-czechoslovakia/",
        "event_date": "2026-04-22",
        "event_end_date": "2026-04-24",
        "location": "Hotel Passage Brno, Brno, Czech Republic",
        "industry_focus": "D&M",
        "relevance_score": 7,
        "scraper_type": "static",
        "event_type_detail": "3-day Conference (largest CZ/SK lean event)",
        "expected_attendees": "400+",
        "audience": "Manufacturing leaders, operations managers, lean/continuous improvement professionals",
        "goal": "Connect with manufacturing decision makers; position Fusion, PDMC, digital transformation",
        "autodesk_relevance": "Fusion, PDMC, Inventor, Vault — manufacturing efficiency and digital transformation",
        "agenda_highlights": "4 parallel streams: Process Excellence, Data-Driven Decisions, Lean Agile, Change Management. Speakers, workshops, case studies, Gemba Walks, evening awards",
        "organizer_contacts": {
            "organizer": "SC&C Partner, spol. s r. o.",
            "general_email": "scacp@scacp.cz",
            "general_phone": "+420 517 541 100",
            "key_contact": "Hana Kalina (Operations Manager)",
            "key_contact_phone": "+420 736 621 587",
            "notes": "Sponsorship tiers available (gold, silver). Hana Kalina manages operations; contact her for attendee list access or partnership.",
        },
        "pages": [{"url": "https://beexcellent.cz/lean-summit-czechoslovakia/"}],
        "fallback_companies": [
            {"company_name": "CommScope", "role": "attendee", "company_domain": "commscope.com"},
            {"company_name": "ALPS Electric Czech", "role": "attendee"},
            {"company_name": "Atlas Copco", "role": "attendee", "company_domain": "atlascopco.com"},
            {"company_name": "Walter s.r.o.", "role": "attendee", "company_domain": "walter-machines.com"},
            {"company_name": "Poclain Hydraulics", "role": "attendee", "company_domain": "poclain.com"},
            {"company_name": "Siemens Energy", "role": "attendee", "company_domain": "siemens-energy.com"},
            {"company_name": "Lufthansa InTouch", "role": "attendee", "company_domain": "lufthansa.com"},
            {"company_name": "VUT Brno", "role": "attendee"},
        ],
    },

    "aerospace_defense": {
        "event_name": "Aerospace & Defense Meetings Brno 2026",
        "url": "https://brno.bciaerospace.com/",
        "event_date": "2026-09-16",
        "event_end_date": "2026-09-17",
        "location": "Brno Exhibition Centre, Brno, Czech Republic",
        "industry_focus": "D&M",
        "relevance_score": 7,
        "scraper_type": "manual",
        "event_type_detail": "B2B Matchmaking Convention (1st edition in Brno)",
        "expected_attendees": "500 participants, 200 companies, 18 countries",
        "audience": "Aerospace & defense OEMs, tier 1-3 suppliers, MRO providers, R&D, procurement",
        "goal": "Meet aerospace manufacturers; position PDMC, Inventor, Vault for complex part design",
        "autodesk_relevance": "Inventor, PDMC, Vault, Moldflow, Fusion — precision engineering for aerospace",
        "agenda_highlights": "3,000 pre-arranged 1-on-1 meetings, conferences, workshops, exhibition",
        "organizer_contacts": {
            "organizer": "BCI Aerospace / Advanced Business Events (France)",
            "event_manager": "Tetyana Bryzhachenko",
            "event_manager_email": "tbryzhachenko@advbe.com",
            "event_manager_phone": "+33 5 32 09 20 00",
            "conference_manager": "Maria Tortajada Chardi",
            "conference_manager_email": "mtortajada@advbe.com",
            "conference_manager_phone": "+33 1 41 86 41 50",
            "marketing_manager": "Emma Hunter",
            "marketing_manager_email": "ehunter@advbe.com",
            "registration_url": "https://meetings.brno.bciaerospace.com/2026/signup.php",
            "notes": "1st edition in Brno. Tetyana Bryzhachenko manages the event — best first contact. All emails @advbe.com domain.",
        },
        "pages": [],
        "fallback_companies": [
            {"company_name": "Honeywell", "role": "regional_partner", "company_domain": "honeywell.com"},
            {"company_name": "Aero Vodochody", "role": "potential_attendee", "company_domain": "aero.cz"},
            {"company_name": "GE Aviation Czech", "role": "potential_attendee"},
            {"company_name": "Safran", "role": "potential_attendee", "company_domain": "safran-group.com"},
            {"company_name": "PBS Velká Bíteš", "role": "potential_attendee", "company_domain": "pbsvb.cz"},
            {"company_name": "LATECOERE Czech Republic", "role": "potential_attendee"},
            {"company_name": "Jihostroj", "role": "potential_attendee", "company_domain": "jihostroj.com"},
        ],
    },

    "brno_industry40": {
        "event_name": "BRNO INDUSTRY 4.0 | 2026",
        "url": "https://www.b2match.com/e/bi40-2026",
        "event_date": "2026-05-21",
        "location": "Hotel International Brno, Husova 16, Brno",
        "industry_focus": "D&M",
        "relevance_score": 8,
        "scraper_type": "manual",
        "event_type_detail": "B2B Matchmaking + Conference (10th edition)",
        "expected_attendees": "200+",
        "audience": "Manufacturing company owners/directors, production/tech directors, digitalization managers — primarily SMEs",
        "goal": "Position Fusion, digital twins, IoT integration; meet I4.0 early adopters",
        "autodesk_relevance": "Fusion, Inventor, Vault, Forma — digital twin and smart manufacturing",
        "price": "Free (funded by South Moravian Region)",
        "agenda_highlights": "Expert talks, thematic workshops, exhibitor booths, panel discussion with production company directors, pre-arranged B2B meetings, networking. Topics: data-driven decisions, cost reduction, AI/automation in practice, predictive maintenance, human-machine collaboration",
        "organizer_contacts": {
            "organizer": "INDUSTRY CLUSTER 4.0, z.s. + Regionální hospodářská komora Brno",
            "program_manager": "Michal Bohátka",
            "program_manager_email": "bohatka@ic40.cz",
            "program_manager_phone": "+420 604 366 171",
            "pr_marketing": "Lenka Votavová",
            "pr_marketing_email": "votavova@ic40.cz",
            "pr_marketing_phone": "+420 532 194 917",
            "cluster_manager": "Radek Kopecký",
            "cluster_manager_email": "kopecky@ic40.cz",
            "cluster_manager_phone": "+420 532 194 923",
            "notes": "Free event. Michal Bohátka is best contact for program/partnership. Ask about speaker slot, booth, or attendee list. Registration open on b2match.",
        },
        "pages": [],
        "fallback_companies": [],
    },

    "digital_factory": {
        "event_name": "Digital Factory 2.0 / MSV 2026",
        "url": "https://www.bvv.cz/en/msv/digital-factory",
        "event_date": "2026-10-06",
        "event_end_date": "2026-10-09",
        "location": "Brno Exhibition Centre (BVV), Brno, Czech Republic",
        "industry_focus": "D&M",
        "relevance_score": 9,
        "scraper_type": "static",
        "event_type_detail": "Trade Fair + Conference (Tue-Fri, part of MSV — largest industrial fair in Central Europe)",
        "expected_attendees": "1,500+ exhibitors, 75,000+ visitors (MSV total), 59 countries",
        "audience": "Manufacturing executives, digital transformation leaders, automation specialists",
        "goal": "Flagship CZ manufacturing event; largest presence opportunity for Autodesk D&M portfolio",
        "autodesk_relevance": "Full D&M portfolio — PDMC, Fusion, Inventor, Vault, PowerMill, Moldflow",
        "agenda_highlights": "Digital Factory 2.0 pavilion, machining/forming demos, Industry 4.0 exhibits, international delegations",
        "organizer_contacts": {
            "organizer": "Veletrhy Brno, a.s. (BVV Trade Fairs Brno)",
            "general_email": "msv@bvv.cz",
            "general_phone": "+420 541 152 926",
            "project_director": "Michalis Busios",
            "project_director_email": "mbusios@bvv.cz",
            "project_director_phone": "+420 541 152 927",
            "project_managers": [
                {"name": "Karin Broučková", "email": "kbrouckova@bvv.cz", "phone": "+420 541 152 936"},
                {"name": "Pavel Dokládal", "email": "pdokladal@bvv.cz", "phone": "+420 541 152 571"},
                {"name": "Nikola Lekovski", "email": "nlekovski@bvv.cz", "phone": "+420 602 768 616"},
            ],
            "notes": "BVV is the venue operator. Michalis Busios is Project Director for MSV. For exhibitor registration use ibap.bvv.cz. Attendee list likely via Busios or project managers.",
        },
        "pages": [{"url": "https://www.bvv.cz/en/msv/digital-factory"}],
        "fallback_companies": [
            {"company_name": "Siemens", "role": "exhibitor", "company_domain": "siemens.com"},
            {"company_name": "Skoda Auto", "role": "exhibitor", "company_domain": "skoda-auto.com"},
            {"company_name": "T-Mobile", "role": "exhibitor", "company_domain": "t-mobile.cz"},
            {"company_name": "KUKA", "role": "exhibitor", "company_domain": "kuka.com"},
            {"company_name": "DEL", "role": "exhibitor", "company_domain": "del.cz"},
            {"company_name": "Pharis", "role": "exhibitor"},
            {"company_name": "Ceska sporitelna", "role": "partner"},
            {"company_name": "EIT Manufacturing", "role": "partner"},
            {"company_name": "Smart Informatics", "role": "exhibitor"},
            {"company_name": "RICAIP", "role": "partner"},
            {"company_name": "Narodni centrum Prumyslu 4.0", "role": "partner"},
            {"company_name": "CONTEG TSE", "role": "speaker_company"},
            {"company_name": "Twinzo", "role": "speaker_company", "company_domain": "twinzo.eu"},
            {"company_name": "HE Consulting", "role": "speaker_company"},
            {"company_name": "Innogy", "role": "speaker_company"},
            {"company_name": "NenoVision", "role": "speaker_company"},
            {"company_name": "Spacemanic", "role": "speaker_company"},
            {"company_name": "SMAUT Technology", "role": "speaker_company"},
            {"company_name": "Neuron Soundware", "role": "speaker_company"},
        ],
    },

    "formy_plasty": {
        "event_name": "Formy a Plasty 2026",
        "url": "https://jansvoboda.cz/rfp",
        "event_date": "2026-05-14",
        "event_end_date": "2026-05-15",
        "location": "Hotel MAXIMUS, Brno, Czech Republic",
        "industry_focus": "D&M",
        "relevance_score": 7,
        "scraper_type": "manual",
        "event_type_detail": "Conference (15th edition)",
        "expected_attendees": "200+",
        "audience": "Mold makers, injection molding specialists, plastics engineers",
        "goal": "Position Moldflow, Fusion, PowerMill for mold & die design",
        "autodesk_relevance": "Moldflow, Fusion, PowerMill, FeatureCAM — mold design and simulation",
        "agenda_highlights": "Technical talks on injection molding, communication/processes, cost-loss identification. Organized by Jan Svoboda s.r.o.",
        "organizer_contacts": {
            "organizer": "JAN SVOBODA s.r.o.",
            "director_1": "Ing. Jan Svoboda, CSc. (jednatel)",
            "director_1_email": "jansvoboda@jansvoboda.cz",
            "director_1_phone": "+420 602 559 576",
            "director_2": "Ing. Jan Svoboda, MBA (jednatel)",
            "director_2_email": "svoboda@jansvoboda.cz",
            "director_2_phone": "+420 724 286 611",
            "registration_contact": "Mgr. Lenka Tycová (marketing)",
            "registration_email": "tycova@jansvoboda.cz",
            "registration_phone": "+420 607 780 610",
            "general_phone": "+420 549 243 939",
            "registration_deadline": "2026-05-07",
            "notes": "Small niche conference (15th edition). Lenka Tycová handles registration and marketing. Directors for partnership/sponsorship talks.",
        },
        "pages": [],
        "fallback_companies": [],
    },

    # -----------------------------------------------------------------------
    # NEW EVENTS — discovered via deep research (April-October 2026)
    # -----------------------------------------------------------------------

    "united_innovation": {
        "event_name": "United by Innovation 2026",
        "url": "https://www.ncp40.cz/udalosti/den-otevrenych-dveri-pro-prumysl-40-ostrava",
        "event_date": "2026-05-14",
        "location": "CPIT TL3, VŠB – Technická univerzita Ostrava, Ostrava-Poruba",
        "industry_focus": "D&M",
        "relevance_score": 7,
        "scraper_type": "manual",
        "event_type_detail": "Conference + Lab Tours (1st edition in Moravian-Silesian region)",
        "expected_attendees": "200+",
        "audience": "Industry 4.0 adopters, researchers, smart factory leaders, automation engineers",
        "goal": "Position Fusion and digital twins; meet I4.0 research-industry crossover audience",
        "autodesk_relevance": "Fusion, Inventor, PDMC — digital twin and smart manufacturing",
        "price": "Free with registration",
        "agenda_highlights": "Strategic discussions, innovation trade fair, guided CPIT TL3 lab tours, networking. Topics: AI, geopolitics, energy resilience, technological sovereignty",
        "organizer_contacts": {
            "organizer": "Národní centrum Průmyslu 4.0 (NCP 4.0) + VŠB-TU Ostrava",
            "general_email": "ncp40@ciirc.cvut.cz",
            "general_phone": "+420 224 354 255",
            "director": "Robert Keil (Director NCP 4.0)",
            "director_email": "robert.keil@cvut.cz",
            "director_phone": "+420 721 416 526",
            "events_contact": "Mgr. Nela Klimešová (event & communication specialist)",
            "events_contact_phone": "+420 605 135 320",
            "events_contact_email": "nela.klimesova@cvut.cz",
            "industry_manager": "Ing. Alena Janošíková (senior industry manager)",
            "industry_manager_phone": "+420 775 983 842",
            "industry_manager_email": "alena.buresova@cvut.cz",
            "notes": "Free event with registration. Nela Klimešová handles events. Alena Janošíková for industry partnerships. Robert Keil is director.",
        },
        "pages": [],
        "fallback_companies": [
            {"company_name": "National Center for Industry 4.0", "role": "organizer", "company_domain": "ncp40.cz"},
            {"company_name": "VŠB-TU Ostrava", "role": "organizer"},
            {"company_name": "CEITEC", "role": "partner"},
            {"company_name": "RICAIP Testbed Prague", "role": "partner"},
            {"company_name": "Siemens", "role": "partner", "company_domain": "siemens.com"},
            {"company_name": "KUKA", "role": "partner", "company_domain": "kuka.com"},
            {"company_name": "Škoda Auto", "role": "partner", "company_domain": "skoda-auto.com"},
            {"company_name": "T-Mobile", "role": "partner", "company_domain": "t-mobile.cz"},
            {"company_name": "Smart Informatics", "role": "partner"},
            {"company_name": "DEL", "role": "partner"},
            {"company_name": "EIT Manufacturing", "role": "partner"},
            {"company_name": "Pharis", "role": "partner"},
            {"company_name": "Česká spořitelna", "role": "partner", "company_domain": "csas.cz"},
        ],
    },

    "digi_bim_day": {
        "event_name": "Digi/BIM Day CKA 2026",
        "url": "https://www.cka.cz/komora/tema-CKA/digi-bim-day-cka-2026",
        "event_date": "2026-05-21",
        "location": "Faculty of Architecture ČVUT, Thákurova 9, Praha-Dejvice (+ online)",
        "industry_focus": "AEC",
        "relevance_score": 9,
        "scraper_type": "manual",
        "event_type_detail": "Full-day Conference (hybrid: in-person + online)",
        "expected_attendees": "140+ (46 in-person, 94 online in 2025)",
        "audience": "Architects, BIM managers, project designers, digital transformation leads",
        "goal": "Position Revit, Forma, ACC directly to Czech Chamber of Architects members",
        "autodesk_relevance": "Revit, Forma, ACC, AEC Collection — AI, generative design, digital building permits",
        "agenda_highlights": "8:00-18:00 full day: lecture blocks, lunch, networking reception with wine. Topics: AI, generative design, digital building permits, robotic fabrication, 3D printing, sustainable design",
        "organizer_contacts": {
            "organizer": "Česká komora architektů (ČKA) + FA ČVUT Prague",
            "cka_general_email": "info@cka.cz",
            "cka_general_phone": "+420 273 167 480",
            "cka_address": "Josefská 34/6, Praha 1",
            "digitalization_group_chair": "Aleš Marek (PS Digitalizace chair)",
            "digitalization_contact": "Kateřina Slané",
            "press_spokesperson": "Mgr. Barbora Sedlářová",
            "press_phone": "+420 777 464 453",
            "notes": "CKA is the professional chamber — attendees are authorized architects. Aleš Marek chairs the Digitalization group that runs this event. Contact info@cka.cz for partnership/speaker slot.",
        },
        "pages": [],
        "fallback_companies": [
            {"company_name": "Czech Chamber of Architects (CKA)", "role": "organizer"},
            {"company_name": "CTU Prague - Faculty of Architecture", "role": "organizer"},
            {"company_name": "Prague Institute of Planning and Development", "role": "speaker"},
            {"company_name": "Mendel University Brno", "role": "speaker"},
            {"company_name": "CodingARCH", "role": "speaker"},
            {"company_name": "landschaft ID GmbH", "role": "speaker"},
        ],
    },

    "urbis_smart_cities": {
        "event_name": "URBIS Smart Cities 2026",
        "url": "https://www.bvv.cz/urbis/",
        "event_date": "2026-06-02",
        "event_end_date": "2026-06-04",
        "location": "Pavilon V, Brno Exhibition Centre (BVV), Brno",
        "industry_focus": "AEC",
        "relevance_score": 8,
        "scraper_type": "manual",
        "event_type_detail": "Trade Fair + 3-day Conference",
        "expected_attendees": "5,000+ visitors, 200+ exhibitors, 400+ speakers, 500+ municipalities",
        "audience": "Municipal leaders, city planners, infrastructure managers, smart city vendors",
        "goal": "Position Civil 3D, InfraWorks, Forma for smart city infrastructure and urban planning",
        "autodesk_relevance": "Civil 3D, InfraWorks, Forma, AEC Collection — infrastructure and urban planning",
        "agenda_highlights": "3-day conference + exhibition + demos. Topics: resilient cities, digital governance, community energy, AI for municipalities, climate-neutral cities, urban planning tools. Cooperation with multiple ministries",
        "organizer_contacts": {
            "organizer": "Veletrhy Brno, a.s. (BVV Trade Fairs Brno)",
            "project_manager": "Jana Kornetová",
            "project_manager_email": "jkornetova@bvv.cz",
            "project_manager_phone": "+420 724 841 697",
            "business_dev": "Petr Maliňák",
            "business_dev_email": "pmalinak@bvv.cz",
            "business_dev_phone": "+420 541 152 979",
            "notes": "Jana Kornetová is the key contact for partnership/exhibitor inquiries. Partnership packages include exhibition space, conference tickets, and social evening. Petr Maliňák handles exhibitor applications.",
        },
        "pages": [],
        "fallback_companies": [
            {"company_name": "3L Robotics", "role": "exhibitor"},
            {"company_name": "Adaptive Recognition", "role": "exhibitor"},
            {"company_name": "ADAPTO.space", "role": "exhibitor"},
            {"company_name": "Agdata", "role": "exhibitor"},
            {"company_name": "Agiception", "role": "exhibitor"},
            {"company_name": "AirView", "role": "exhibitor"},
            {"company_name": "ALFA PROFI", "role": "exhibitor"},
            {"company_name": "CzechInvest", "role": "exhibitor"},
            {"company_name": "Teplárny Brno", "role": "general_partner", "company_domain": "teplarny.cz"},
            {"company_name": "EasyPark Czechia", "role": "exhibitor"},
            {"company_name": "Asseco Central Europe", "role": "exhibitor", "company_domain": "asseco.com"},
            {"company_name": "BC LOGIA", "role": "exhibitor"},
            {"company_name": "Hyverr", "role": "exhibitor"},
            {"company_name": "ANTHONYapp", "role": "exhibitor"},
            {"company_name": "CEDA Maps", "role": "exhibitor"},
            {"company_name": "Sensority", "role": "exhibitor"},
            {"company_name": "Technické sítě Brno", "role": "exhibitor"},
            {"company_name": "CODE TEAM", "role": "exhibitor"},
            {"company_name": "Panda energy management", "role": "exhibitor"},
            {"company_name": "BVV Trade Fairs Brno", "role": "organizer"},
            {"company_name": "City of Brno", "role": "partner"},
            {"company_name": "Ministry of Regional Development", "role": "partner"},
        ],
    },

    "architect_at_work": {
        "event_name": "Architect@Work Prague 2026",
        "url": "https://www.architectatwork.cz/",
        "event_date": "2026-06-17",
        "event_end_date": "2026-06-18",
        "location": "Prague, Czech Republic",
        "industry_focus": "AEC",
        "relevance_score": 8,
        "scraper_type": "manual",
        "event_type_detail": "Curated Exhibition (invitation-only for exhibitors, open to verified architects)",
        "expected_attendees": "2,000+",
        "audience": "Architects, interior designers, specifiers, design professionals",
        "goal": "Showcase Revit, Forma, 3ds Max visualization to high-end architecture audience",
        "autodesk_relevance": "Revit, Forma, 3ds Max (visualization), AEC Collection — design innovation",
        "agenda_highlights": "Pre-selected innovative products, academy seminars, moodboard/Xperience platform, networking",
        "organizer_contacts": {
            "organizer": "Xpo Organizations Czech s.r.o. (part of Xpo Group BV)",
            "general_email": "czechrepublic@architectatwork.com",
            "phone": "+420 229 010 241",
            "sr_exhibition_manager": "Hannelore Caenepeel",
            "account_manager": "Magda Horčicová",
            "address": "Antala Staška 1859/34, Praha 4 – Krč, 140 00",
            "venue": "PVA EXPO PRAHA",
            "notes": "Curated exhibition — exhibitors must apply and be pre-selected. Contact czechrepublic@ for exhibitor application or visitor pass. Magda Horčicová is local account manager.",
        },
        "pages": [],
        "fallback_companies": [
            {"company_name": "Czech Chamber of Architects", "role": "patron"},
        ],
    },

    "for_arch": {
        "event_name": "FOR ARCH 2026",
        "url": "https://forarch.cz/",
        "event_date": "2026-09-16",
        "event_end_date": "2026-09-19",
        "location": "PVA EXPO PRAHA, Prague, Czech Republic",
        "industry_focus": "AEC",
        "relevance_score": 9,
        "scraper_type": "manual",
        "event_type_detail": "Trade Fair (37th edition, Wed-Sat — new schedule)",
        "expected_attendees": "39,000+ visitors, 525+ exhibitors",
        "audience": "Builders, developers, architects, engineers, construction material suppliers",
        "goal": "Largest CZ construction fair — broad AEC audience for Revit, AutoCAD, AEC Collection",
        "autodesk_relevance": "Revit, AutoCAD, AEC Collection, BIM Collaborate Pro, Navisworks — full AEC",
        "agenda_highlights": "Sectors: building materials, HVAC, electrical/security, timber construction, pools/spa. Includes FOR INTERIOR co-event",
        "organizer_contacts": {
            "organizer": "ABF, a.s.",
            "sales_director": "Vanda Petrov",
            "sales_director_email": "petrov@abf.cz",
            "sales_lead": "Martin Pavlata",
            "sales_lead_email": "pavlata@abf.cz",
            "sales_lead_phone": "+420 792 925 847",
            "fair_managers": [
                {"name": "Petr Váša", "email": "vasa@abf.cz", "phone": "+420 724 581 291"},
                {"name": "Veronika Vacková", "email": "vackova@abf.cz", "phone": "+420 721 942 100"},
                {"name": "Danilo Kažič", "email": "kazic@abf.cz"},
                {"name": "Regina Fibichová", "email": "fibichova@abf.cz", "phone": "+420 602 302 771"},
                {"name": "Dominika Košťálová", "phone": "+420 720 315 315"},
            ],
            "address": "Beranových 667, 199 00 Praha 9 – Letňany",
            "notes": "Largest CZ construction fair. Contact Vanda Petrov (Sales Director) or Martin Pavlata for exhibitor/partnership. 525 exhibitors + 39K visitors — attendee list likely via ABF partnership agreement.",
        },
        "pages": [],
        "fallback_companies": [
            {"company_name": "OBZOR Zlín", "role": "exhibitor"},
            {"company_name": "MC VELOX Praha", "role": "exhibitor"},
            {"company_name": "LAMARK", "role": "exhibitor"},
            {"company_name": "BSG", "role": "exhibitor"},
            {"company_name": "SMAR", "role": "exhibitor"},
            {"company_name": "Isover", "role": "exhibitor", "company_domain": "isover.cz"},
            {"company_name": "Xella CZ", "role": "exhibitor", "company_domain": "xella.cz"},
        ],
    },

    "bim_day": {
        "event_name": "BIM DAY 2026",
        "url": "https://www.bimday.cz/",
        "event_date": "2026-10-20",
        "event_end_date": "2026-10-21",
        "location": "OREA Hotel Pyramida, Bělohorská 24, Praha 6",
        "industry_focus": "AEC",
        "relevance_score": 10,
        "scraper_type": "manual",
        "event_type_detail": "2-day Conference + Workshops + BIM Market",
        "expected_attendees": "500+",
        "audience": "BIM managers, architects, engineers, construction digitalization leaders",
        "goal": "Premier CZ BIM conference — position full AEC portfolio to buildingSMART community",
        "autodesk_relevance": "Revit, ACC, BIM Collaborate Pro, Forma, Navisworks — full BIM workflow",
        "price": "2-day pass: 9,990 CZK; 1-day: 6,290 CZK; czBIM members: 6,290 CZK/2 days; Gala evening: 2,750 CZK (all + 21% VAT)",
        "agenda_highlights": "Keynotes from European + Czech BIM experts, workshops, BIM Market exhibition, gala evening (Oct 20). Organized by czBIM / buildingSMART Czech Republic",
        "organizer_contacts": {
            "organizer": "czBIM (Odborná rada pro BIM, z.s.) — buildingSMART Czech Republic",
            "general_email": "office@czbim.org",
            "board_email": "predstavenstvo@czbim.org",
            "operations_director": "Mgr. Libuše Kalkus Kameníčková",
            "operations_director_email": "kamenickova@czbim.org",
            "operations_director_email_alt": "tajemnik@czbim.org",
            "operations_director_phone": "+420 777 950 853",
            "board_chairman": "Ing. Petr Matyáš",
            "board_chairman_phone": "+420 603 552 532",
            "address": "Biskupský dvůr 1148, 110 00 Praha 1 (office); Thákurova 7/2077, 166 29 Praha 6 (legal)",
            "notes": "Libuše Kameníčková is the Operations Director — best contact for program, partnership, and attendee lists. Petr Matyáš is Board Chairman for high-level partnership talks. Autodesk is a natural partner.",
        },
        "pages": [],
        "fallback_companies": [
            {"company_name": "czBIM / buildingSMART CZ", "role": "organizer"},
            {"company_name": "Trimble", "role": "workshop_presenter", "company_domain": "trimble.com"},
            {"company_name": "Construsoft", "role": "workshop_presenter", "company_domain": "construsoft.com"},
            {"company_name": "AFRY CZ", "role": "workshop_presenter", "company_domain": "afry.com"},
            {"company_name": "SCAN4BIM", "role": "workshop_presenter"},
            {"company_name": "Gefos", "role": "workshop_presenter", "company_domain": "gefos.cz"},
            {"company_name": "cadconsulting", "role": "speaker", "company_domain": "cadconsulting.cz"},
            {"company_name": "di5 architekti inženýři", "role": "speaker"},
            {"company_name": "GLEEDS ČESKÁ REPUBLIKA", "role": "speaker"},
            {"company_name": "AED project", "role": "workshop_presenter", "company_domain": "aed-project.cz"},
            {"company_name": "BIM Project", "role": "moderator"},
            {"company_name": "PORR a.s.", "role": "speaker", "company_domain": "porr.cz"},
            {"company_name": "CADservis", "role": "workshop_presenter", "company_domain": "cadservis.cz"},
            {"company_name": "Česká spořitelna", "role": "case_study", "company_domain": "csas.cz"},
            {"company_name": "Letiště Václava Havla Praha", "role": "speaker"},
            {"company_name": "Správa železnic", "role": "speaker"},
            {"company_name": "Technická správa komunikací hl. m. Prahy", "role": "speaker"},
            {"company_name": "Česká agentura pro standardizaci", "role": "speaker"},
            {"company_name": "Projects 4GASTRONOMY", "role": "workshop_presenter"},
            {"company_name": "ČS NHQ", "role": "case_study"},
            {"company_name": "Leica Geosystems", "role": "workshop_presenter", "company_domain": "leica-geosystems.com"},
            {"company_name": "MFS DX", "role": "workshop_presenter"},
            {"company_name": "Bim.Point", "role": "workshop_presenter"},
        ],
    },

    "designblok": {
        "event_name": "Designblok 2026",
        "url": "https://www.designblok.cz/en/",
        "event_date": "2026-10-06",
        "event_end_date": "2026-10-11",
        "location": "Křižík Pavilions + Prague Castle (Royal Summer Palace), Prague",
        "industry_focus": "M&E",
        "relevance_score": 6,
        "scraper_type": "manual",
        "event_type_detail": "Design Festival (28th edition, theme: 'Light')",
        "expected_attendees": "50,000+ (record attendance in 2025)",
        "audience": "Designers, architects, artists, creative professionals, design students",
        "goal": "Connect with creative professionals; showcase 3ds Max visualization, Alias, Forma",
        "autodesk_relevance": "3ds Max, Alias, Forma — visualization, industrial design, creative tools",
        "agenda_highlights": "6-day festival: Superstudio, High Craft exhibition (curated with Vogue CS), Designblok Talks conference (Oct 7), guest speakers incl. Erwan Bouroullec, Patricia Urquiola",
        "organizer_contacts": {
            "organizer": "Profil Media s.r.o.",
            "director": "Jana Zielinski (Festival Director)",
            "partnership_contact": "Světla Novotná (Executive Director & Partnerships)",
            "partnership_email": "svetla.novotna@profilmedia.cz",
            "partnership_phone": "+420 777 944 962",
            "partnership_email_alt": "partnerstvi@profilmedia.cz",
            "general_email": "info@designblok.cz",
            "notes": "50K+ visitors. Contact Světla Novotná for partnership/exhibitor inquiries. Jana Zielinski is the creative director. Explore sponsorship or Designblok Talks speaker slot.",
        },
        "pages": [],
        "fallback_companies": [],
    },

    "cadforum_2026": {
        "event_name": "CADforum 2026 (Arkance Systems)",
        "url": "https://konference.cadforum.cz/",
        "event_date": "2026-09-29",
        "location": "Czech Republic (2025: Hotel Valeč, Vysočina — 2026 TBC)",
        "industry_focus": "mixed",
        "relevance_score": 9,
        "scraper_type": "manual",
        "event_type_detail": "1-day Conference + Evening Program (23rd edition expected)",
        "expected_attendees": "300+ (99% return rate in surveys)",
        "audience": "Arkance/CAD Studio customers across AEC, D&M — engineers, architects, BIM managers",
        "goal": "Autodesk reseller flagship event — get attendee list, present, network with existing users",
        "autodesk_relevance": "Full Autodesk portfolio — all segments. Customer case studies and new features",
        "price": "Paid (amount TBC for 2026)",
        "agenda_highlights": "Based on 2025: keynote on AI/digital trends, AEC track (Revit, Civil 3D, BIM, Scan-to-BIM), MFG track (Inventor, Fusion, CAM, PLM, MES), Autodesk developer workshop, tombola, casino evening. Moderated by Boris Keka",
        "organizer_contacts": {
            "organizer": "ARKANCE CZ/SK (formerly CAD Studio) + Autodesk",
            "managing_director": "Renata Dvořáková (Managing Director ARKANCE CZ/SK)",
            "general_email": "info.cz@arkance.world",
            "general_phone": "+420 910 970 111",
            "autodesk_speaker_2025": "Patrik Minks (Territory Sales Executive, Autodesk)",
            "notes": "This is Autodesk's own reseller event — Arkance is the #1 Autodesk partner in CEE. Renata Dvořáková is the key decision maker. 99% attendee return rate. Attendee list should be accessible via internal Autodesk-Arkance relationship. Ask Patrik Minks (Autodesk) directly.",
        },
        "pages": [],
        "fallback_companies": [
            {"company_name": "Arkance Systems", "role": "organizer", "company_domain": "arkance.world"},
            {"company_name": "CAD Studio", "role": "organizer", "company_domain": "cadstudio.cz"},
        ],
    },

    "interpack": {
        "event_name": "interpack 2026",
        "url": "https://www.interpack.com/",
        "event_date": "2026-05-07",
        "event_end_date": "2026-05-13",
        "location": "Messe Düsseldorf, Düsseldorf, Germany",
        "industry_focus": "D&M",
        "relevance_score": 8,
        "scraper_type": "json_fallback",
        "event_type_detail": "Trade Fair (world's leading packaging trade show)",
        "expected_attendees": "2,800+ exhibitors, 170,000+ visitors",
        "audience": "Packaging machinery, processing technology, materials OEMs, F&B, pharma, cosmetics",
        "goal": "Meet packaging machinery manufacturers; position Inventor, Fusion, Vault, PDMC for machine design",
        "autodesk_relevance": "Inventor, Fusion, PDMC, Vault, PowerMill — packaging machine design and manufacturing",
        "agenda_highlights": "7-day fair: SPOTLIGHT Forum, Start-Up Zone, SAVE FOOD, WorldStar Awards, live demos, workshops",
        "organizer_contacts": {
            "organizer": "Messe Düsseldorf GmbH",
            "general_email": "info@messe-duesseldorf.de",
            "general_phone": "+49 211 4560-01",
            "notes": "World's largest packaging trade fair. Czech exhibitors: IMACO Group, J4 s.r.o., MILCOM MILPACK, NOMATECH, Papírna Aloisov, Pebal, Velteko, Viking Masek.",
        },
        "pages": [],
        "fallback_json": "interpack_exhibitors.json",
        "fallback_companies": [],
    },
}
